#!/bin/sh -e

wget -O- http://distro.ibiblio.org/puppylinux/sources/g/gnome-menus-2.14.3.tar.bz2 | tar -xjf-
cd gnome-menus-2.14.3
./configure --prefix=/usr --disable-python
make install

# force static linking, we're using an old version and don't want it to conflict with a later version
rm -f /usr/lib/libgnome-menu.so*

wget -O- http://distro.ibiblio.org/puppylinux/sources/x/xdg_puppy-0.7.6-9.tar.bz2 | tar -xjf-
cd xdg_puppy-0.7.6-9/jwm-xdgmenu
gcc $CFLAGS -DGMENU_I_KNOW_THIS_IS_UNSTABLE `pkg-config --cflags glib-2.0 libgnome-menu` jwm-xdgmenu.c $LDFLAGS `pkg-config --libs glib-2.0 libgnome-menu` -o /usr/bin/jwm-xdgmenu

# we don't need these
rm -rf /usr/bin/gnome-menu-spec-test /usr/lib /usr/include /usr/share/locale