#!/bin/sh

# debian/ubuntu
if [ -f usr/lib/${ARCHDIR}/libgtk-3-0/gtk-query-immodules-3.0 ] ; then
	mkdir -p usr/bin
	ln -sv ../lib/${ARCHDIR}/libgtk-3-0/gtk-query-immodules-3.0 \
			usr/bin/gtk-query-immodules-3.0
fi

#xenial
if [ -f usr/bin/gtk-update-icon-cache-3.0 -a ! -e usr/bin/gtk-update-icon-cache ] ; then
	ln -sv gtk-update-icon-cache-3.0 usr/bin/gtk-update-icon-cache
fi

# raleigh-reloaded and possibly other themes need the arrow symbolic icons
if [ -d usr/share/icons/Adwaita ]; then
	cd usr/share/icons/Adwaita
	rm -rf [0-9]*x* cursor* scalable-*
	find scalable -type f | while read ICON; do
		case $ICON in
		*/pan-*) ;;
		*) rm -f $ICON ;;
		esac
	done
	rmdir scalable/* 2>/dev/null
	cd ../../../..
fi
