#!/bin/sh -e

wget -O- http://dist.schmorp.de/rxvt-unicode/rxvt-unicode-9.22.tar.bz2 | tar -xjf-
cd rxvt-unicode-9.22
./configure --prefix=/usr --disable-pixbuf --disable-startup-notification --disable-perl --disable-frills --disable-utmp --disable-wtmp --disable-lastlog
make install
rm -f /usr/bin/urxvtd /usr/bin/urxvtc
install -D -m 644 ../Urxvt-terminal-emulator.desktop /usr/share/applications/Urxvt-terminal-emulator.desktop