#!/bin/sh -e

wget -O- http://distro.ibiblio.org/puppylinux/sources/g/gtkdialog-0.8.4a.tar.xz | tar -xJf-
cd gtkdialog-0.8.4a
patch -p1 < ../globals.patch
patch -p1 < ../no-doc.patch
./configure --prefix=/usr --bindir=/usr/sbin
make install