#!/bin/sh -e

wget -O- https://github.com/puppylinux-woof-CE/rox-filer/archive/rox-filer-17w.tar.gz | tar -xzf-
cd rox-filer-rox-filer-17w
patch -p1 < ../extern.patch
cd ROX-Filer
yes "" | ./AppRun --compile
cd src/po
for LANG in de fr es; do
    ./make-mo $LANG
done
cd ../..
mkdir -p /usr/local/apps/ROX-Filer
cp -af Help images ROX AppInfo.xml AppRun .DirIcon Options.xml style.css subclasses Templates.glade Templates.ui ROX-Filer Messages /usr/local/apps/ROX-Filer/